from django.core.management.base import BaseCommand

from core.models import TipoEstudio


# Catálogo maestro de Loreto One.
# Fuente: catálogo proporcionado para IDUGON.
# Puede ejecutarse varias veces sin duplicar registros.
CATALOGO = [
    ('RX001', 'RX tórax PA', 'RX', 10),
    ('RX002', 'RX tórax AP', 'RX', 10),
    ('RX003', 'RX tórax PA/LAT', 'RX', 10),
    ('RX004', 'RX tórax AP/LAT', 'RX', 10),
    ('RX005', 'RX tórax portátil AP', 'RX', 10),
    ('RX006', 'RX tórax lordótica', 'RX', 10),
    ('RX007', 'RX parrilla costal AP/OBL', 'RX', 10),
    ('RX008', 'RX parrilla costal PA/OBL', 'RX', 10),
    ('RX009', 'RX esternón PA/OBL', 'RX', 10),
    ('RX010', 'RX abdomen AP', 'RX', 10),
    ('RX011', 'RX abdomen de pie AP', 'RX', 10),
    ('RX012', 'RX abdomen decúbito AP', 'RX', 10),
    ('RX013', 'RX abdomen AP/LAT', 'RX', 10),
    ('RX014', 'RX abdomen serie simple', 'RX', 10),
    ('RX015', 'RX columna cervical AP/LAT', 'RX', 10),
    ('RX016', 'RX columna cervical AP/LAT/OBL', 'RX', 10),
    ('RX017', 'RX columna cervical AP/LAT/transoral', 'RX', 10),
    ('RX018', 'RX columna cervical funcional AP/LAT flexión-extensión', 'RX', 10),
    ('RX019', 'RX columna torácica AP/LAT', 'RX', 10),
    ('RX020', 'RX columna lumbar AP/LAT', 'RX', 10),
    ('RX021', 'RX columna lumbar AP/LAT/OBL', 'RX', 10),
    ('RX022', 'RX columna lumbosacra AP/LAT', 'RX', 10),
    ('RX023', 'RX columna lumbosacra AP/LAT/OBL', 'RX', 10),
    ('RX024', 'RX sacro AP/LAT', 'RX', 10),
    ('RX025', 'RX cóccix AP/LAT', 'RX', 10),
    ('RX026', 'RX sacro-cóccix AP/LAT', 'RX', 10),
    ('RX027', 'RX columna total AP/LAT', 'RX', 10),
    ('RX028', 'RX columna total AP', 'RX', 10),
    ('RX029', 'RX escoliosis AP/LAT', 'RX', 10),
    ('RX030', 'RX escoliosis de pie AP', 'RX', 10),
    ('RX031', 'RX escoliosis funcional/inclinaciones', 'RX', 10),
    ('RX032', 'RX pelvis AP', 'RX', 10),
    ('RX033', 'RX pelvis AP/OBL', 'RX', 10),
    ('RX034', 'RX cadera AP/LAT', 'RX', 10),
    ('RX035', 'RX cadera bilateral AP/LAT', 'RX', 10),
    ('RX036', 'RX cadera AP/axial', 'RX', 10),
    ('RX037', 'RX cadera AP/LAT rana', 'RX', 10),
    ('RX038', 'RX pelvis AP/LAT rana', 'RX', 10),
    ('RX039', 'RX articulaciones sacroilíacas AP/OBL', 'RX', 10),
    ('RX040', 'RX hombro AP', 'RX', 10),
    ('RX041', 'RX hombro AP/LAT', 'RX', 10),
    ('RX042', 'RX hombro AP/OBL', 'RX', 10),
    ('RX043', 'RX hombro AP/axial', 'RX', 10),
    ('RX044', 'RX hombro AP/Y escapular', 'RX', 10),
    ('RX045', 'RX clavícula AP', 'RX', 10),
    ('RX046', 'RX clavícula AP/axial', 'RX', 10),
    ('RX047', 'RX articulación acromioclavicular AP', 'RX', 10),
    ('RX048', 'RX articulaciones acromioclaviculares comparativas', 'RX', 10),
    ('RX049', 'RX escápula AP/LAT', 'RX', 10),
    ('RX050', 'RX húmero AP/LAT', 'RX', 10),
    ('RX051', 'RX codo AP/LAT', 'RX', 10),
    ('RX052', 'RX codo AP/LAT/OBL', 'RX', 10),
    ('RX053', 'RX antebrazo AP/LAT', 'RX', 10),
    ('RX054', 'RX muñeca PA/LAT', 'RX', 10),
    ('RX055', 'RX muñeca PA/LAT/OBL', 'RX', 10),
    ('RX056', 'RX muñeca PA/LAT/escafoides', 'RX', 10),
    ('RX057', 'RX mano PA/OBL', 'RX', 10),
    ('RX058', 'RX mano PA/LAT/OBL', 'RX', 10),
    ('RX059', 'RX mano bilateral PA', 'RX', 10),
    ('RX060', 'RX dedos PA/LAT/OBL', 'RX', 10),
    ('RX061', 'RX pulgar AP/LAT/OBL', 'RX', 10),
    ('RX062', 'RX edad ósea mano y muñeca izquierda PA', 'RX', 10),
    ('RX063', 'RX fémur AP/LAT', 'RX', 10),
    ('RX064', 'RX rodilla AP/LAT', 'RX', 10),
    ('RX065', 'RX rodilla AP/LAT/OBL', 'RX', 10),
    ('RX066', 'RX rodilla AP/LAT/axial de rótula', 'RX', 10),
    ('RX067', 'RX rodillas AP comparativas', 'RX', 10),
    ('RX068', 'RX rodillas AP de pie', 'RX', 10),
    ('RX069', 'RX rodillas AP de pie/LAT', 'RX', 10),
    ('RX070', 'RX rótula AP/LAT/axial', 'RX', 10),
    ('RX071', 'RX pierna AP/LAT', 'RX', 10),
    ('RX072', 'RX tobillo AP/LAT', 'RX', 10),
    ('RX073', 'RX tobillo AP/LAT/OBL', 'RX', 10),
    ('RX074', 'RX tobillo AP/LAT/mortaja', 'RX', 10),
    ('RX075', 'RX pie AP/OBL', 'RX', 10),
    ('RX076', 'RX pie AP/LAT/OBL', 'RX', 10),
    ('RX077', 'RX pie AP/LAT', 'RX', 10),
    ('RX078', 'RX pie con apoyo AP/LAT', 'RX', 10),
    ('RX079', 'RX pies con apoyo AP', 'RX', 10),
    ('RX080', 'RX calcáneo axial/LAT', 'RX', 10),
    ('RX081', 'RX dedos del pie AP/LAT/OBL', 'RX', 10),
    ('RX082', 'RX cráneo AP/LAT', 'RX', 10),
    ('RX083', 'RX cráneo PA/LAT', 'RX', 10),
    ('RX084', 'RX cráneo AP/LAT/Towne', 'RX', 10),
    ('RX085', 'RX cráneo PA/LAT/Caldwell', 'RX', 10),
    ('RX086', 'RX senos paranasales Waters', 'RX', 10),
    ('RX087', 'RX senos paranasales Caldwell/Waters/LAT', 'RX', 10),
    ('RX088', 'RX huesos propios de la nariz LAT', 'RX', 10),
    ('RX089', 'RX huesos propios de la nariz AP/LAT', 'RX', 10),
    ('RX090', 'RX macizo facial Waters', 'RX', 10),
    ('RX091', 'RX macizo facial Caldwell/Waters/LAT', 'RX', 10),
    ('RX092', 'RX órbitas PA/Waters', 'RX', 10),
    ('RX093', 'RX órbitas PA/LAT', 'RX', 10),
    ('RX094', 'RX mandíbula PA/OBL', 'RX', 10),
    ('RX095', 'RX mandíbula PA/LAT/OBL', 'RX', 10),
    ('RX096', 'RX articulaciones temporomandibulares', 'RX', 10),
    ('RX097', 'RX arcos cigomáticos', 'RX', 10),
    ('RX098', 'RX mastoides', 'RX', 10),
    ('RX099', 'RX silla turca AP/LAT', 'RX', 10),
    ('RX100', 'RX miembros inferiores AP', 'RX', 10),
    ('RX101', 'RX miembros inferiores AP con carga', 'RX', 10),
    ('RX102', 'RX telemetría de miembros inferiores', 'RX', 10),
    ('RX103', 'RX eje mecánico de miembros inferiores', 'RX', 10),
    ('RX104', 'RX longitud de miembros inferiores', 'RX', 10),
    ('RX105', 'RX columna total AP/LAT de pie', 'RX', 10),
    ('FLUORO001', 'RX esofagograma', 'FLUORO', 30),
    ('FLUORO002', 'RX esofagograma con doble contraste', 'FLUORO', 30),
    ('FLUORO003', 'RX esofagograma con medio hidrosoluble', 'FLUORO', 30),
    ('FLUORO004', 'RX serie esófago-gastroduodenal (SEGD)', 'FLUORO', 30),
    ('FLUORO005', 'RX serie esófago-gastroduodenal con doble contraste', 'FLUORO', 30),
    ('FLUORO006', 'RX tránsito intestinal', 'FLUORO', 30),
    ('FLUORO007', 'RX serie gastrointestinal completa', 'FLUORO', 30),
    ('FLUORO008', 'RX colon por enema', 'FLUORO', 30),
    ('FLUORO009', 'RX colon por enema con doble contraste', 'FLUORO', 30),
    ('FLUORO010', 'RX estudio de deglución', 'FLUORO', 30),
    ('FLUORO011', 'RX fistulografía', 'FLUORO', 30),
    ('FLUORO012', 'RX urografía excretora', 'FLUORO', 30),
    ('FLUORO013', 'RX pielografía intravenosa', 'FLUORO', 30),
    ('FLUORO014', 'RX pielografía retrógrada', 'FLUORO', 30),
    ('FLUORO015', 'RX pielografía anterógrada', 'FLUORO', 30),
    ('FLUORO016', 'RX cistografía', 'FLUORO', 30),
    ('FLUORO017', 'RX cistografía miccional', 'FLUORO', 30),
    ('FLUORO018', 'RX uretrografía retrógrada', 'FLUORO', 30),
    ('FLUORO019', 'RX uretrocistografía', 'FLUORO', 30),
    ('FLUORO020', 'RX uretrocistografía miccional', 'FLUORO', 30),
    ('FLUORO021', 'RX nefrostografía', 'FLUORO', 30),
    ('FLUORO022', 'RX histerosalpingografía (HSG)', 'FLUORO', 30),
    ('FLUORO023', 'RX colangiografía', 'FLUORO', 30),
    ('FLUORO024', 'RX colangiografía transoperatoria', 'FLUORO', 30),
    ('FLUORO025', 'RX colangiografía por tubo en T', 'FLUORO', 30),
    ('FLUORO026', 'RX colangiografía percutánea', 'FLUORO', 30),
    ('FLUORO027', 'RX sialografía', 'FLUORO', 30),
    ('FLUORO028', 'RX dacriocistografía', 'FLUORO', 30),
    ('FLUORO029', 'RX galactografía / ductografía mamaria', 'FLUORO', 30),
    ('FLUORO030', 'RX artrografía de hombro', 'FLUORO', 30),
    ('FLUORO031', 'RX artrografía de codo', 'FLUORO', 30),
    ('FLUORO032', 'RX artrografía de muñeca', 'FLUORO', 30),
    ('FLUORO033', 'RX artrografía de cadera', 'FLUORO', 30),
    ('FLUORO034', 'RX artrografía de rodilla', 'FLUORO', 30),
    ('FLUORO035', 'RX artrografía de tobillo', 'FLUORO', 30),
    ('FLUORO036', 'RX sinografía', 'FLUORO', 30),
    ('FLUORO037', 'RX cavernosografía', 'FLUORO', 30),
    ('FLUORO038', 'RX vaginografía', 'FLUORO', 30),
    ('FLUORO039', 'RX linfangiografía', 'FLUORO', 30),
    ('FLUORO040', 'Fluoroscopia de deglución', 'FLUORO', 30),
    ('FLUORO041', 'Fluoroscopia esofágica', 'FLUORO', 30),
    ('FLUORO042', 'Fluoroscopia gastrointestinal', 'FLUORO', 30),
    ('FLUORO043', 'Fluoroscopia diafragmática', 'FLUORO', 30),
    ('FLUORO044', 'Fluoroscopia para cuerpo extraño', 'FLUORO', 30),
    ('FLUORO045', 'Fluoroscopia de control de catéter', 'FLUORO', 30),
    ('FLUORO046', 'Fluoroscopia para procedimiento', 'FLUORO', 30),
    ('FLUORO047', 'Fluoroscopia transoperatoria', 'FLUORO', 30),
    ('TAC001', 'TAC cráneo simple', 'TAC', 20),
    ('TAC002', 'TAC cráneo simple con reconstrucción ósea', 'TAC', 20),
    ('TAC003', 'TAC senos paranasales simple', 'TAC', 20),
    ('TAC004', 'TAC macizo facial simple', 'TAC', 20),
    ('TAC005', 'TAC macizo facial simple con reconstrucción 3D', 'TAC', 20),
    ('TAC006', 'TAC órbitas simple', 'TAC', 20),
    ('TAC007', 'TAC huesos propios de la nariz simple', 'TAC', 20),
    ('TAC008', 'TAC mandíbula simple', 'TAC', 20),
    ('TAC009', 'TAC articulaciones temporomandibulares simple', 'TAC', 20),
    ('TAC010', 'TAC oídos / peñascos simple', 'TAC', 20),
    ('TAC011', 'TAC mastoides simple', 'TAC', 20),
    ('TAC012', 'TAC cuello simple', 'TAC', 20),
    ('TAC013', 'TAC tejidos blandos de cuello simple', 'TAC', 20),
    ('TAC014', 'TAC columna cervical simple', 'TAC', 20),
    ('TAC015', 'TAC columna torácica simple', 'TAC', 20),
    ('TAC016', 'TAC columna lumbar simple', 'TAC', 20),
    ('TAC017', 'TAC columna lumbosacra simple', 'TAC', 20),
    ('TAC018', 'TAC sacro simple', 'TAC', 20),
    ('TAC019', 'TAC cóccix simple', 'TAC', 20),
    ('TAC020', 'TAC columna completa simple', 'TAC', 20),
    ('TAC021', 'TAC columna simple con reconstrucción 3D', 'TAC', 20),
    ('TAC022', 'TAC tórax simple', 'TAC', 20),
    ('TAC023', 'TAC tórax de alta resolución (TCAR)', 'TAC', 20),
    ('TAC024', 'TAC tórax simple con reconstrucción pulmonar', 'TAC', 20),
    ('TAC025', 'TAC tórax simple con reconstrucción ósea', 'TAC', 20),
    ('TAC026', 'TAC abdomen simple', 'TAC', 20),
    ('TAC027', 'TAC abdomen y pelvis simple', 'TAC', 20),
    ('TAC028', 'TAC pelvis simple', 'TAC', 20),
    ('TAC029', 'TAC vías urinarias simple / UroTAC simple', 'TAC', 20),
    ('TAC030', 'TAC renal simple', 'TAC', 20),
    ('TAC031', 'TAC litiasis renal / protocolo de litiasis', 'TAC', 20),
    ('TAC032', 'TAC hígado simple', 'TAC', 20),
    ('TAC033', 'TAC páncreas simple', 'TAC', 20),
    ('TAC034', 'TAC suprarrenales simple', 'TAC', 20),
    ('TAC035', 'TAC hombro simple', 'TAC', 20),
    ('TAC036', 'TAC húmero simple', 'TAC', 20),
    ('TAC037', 'TAC codo simple', 'TAC', 20),
    ('TAC038', 'TAC antebrazo simple', 'TAC', 20),
    ('TAC039', 'TAC muñeca simple', 'TAC', 20),
    ('TAC040', 'TAC mano simple', 'TAC', 20),
    ('TAC041', 'TAC pelvis ósea simple', 'TAC', 20),
    ('TAC042', 'TAC cadera simple', 'TAC', 20),
    ('TAC043', 'TAC fémur simple', 'TAC', 20),
    ('TAC044', 'TAC rodilla simple', 'TAC', 20),
    ('TAC045', 'TAC pierna simple', 'TAC', 20),
    ('TAC046', 'TAC tobillo simple', 'TAC', 20),
    ('TAC047', 'TAC pie simple', 'TAC', 20),
    ('TAC048', 'TAC cráneo simple y contrastado', 'TAC', 20),
    ('TAC049', 'TAC cráneo contrastado', 'TAC', 20),
    ('TAC050', 'TAC órbitas simple y contrastado', 'TAC', 20),
    ('TAC051', 'TAC senos paranasales simple y contrastado', 'TAC', 20),
    ('TAC052', 'TAC macizo facial simple y contrastado', 'TAC', 20),
    ('TAC053', 'TAC cuello simple y contrastado', 'TAC', 20),
    ('TAC054', 'TAC cuello contrastado', 'TAC', 20),
    ('TAC055', 'TAC tejidos blandos de cuello simple y contrastado', 'TAC', 20),
    ('TAC056', 'TAC tórax simple y contrastado', 'TAC', 20),
    ('TAC057', 'TAC tórax contrastado', 'TAC', 20),
    ('TAC058', 'TAC tórax y abdomen simple y contrastado', 'TAC', 20),
    ('TAC059', 'TAC tórax, abdomen y pelvis simple y contrastado', 'TAC', 20),
    ('TAC060', 'TAC abdomen simple y contrastado', 'TAC', 20),
    ('TAC061', 'TAC abdomen contrastado', 'TAC', 20),
    ('TAC062', 'TAC abdomen y pelvis simple y contrastado', 'TAC', 20),
    ('TAC063', 'TAC abdomen y pelvis contrastado', 'TAC', 20),
    ('TAC064', 'TAC pelvis simple y contrastado', 'TAC', 20),
    ('TAC065', 'TAC pelvis contrastado', 'TAC', 20),
    ('TAC066', 'TAC abdomen trifásico', 'TAC', 20),
    ('TAC067', 'TAC hígado trifásico', 'TAC', 20),
    ('TAC068', 'TAC protocolo hepático multifásico', 'TAC', 20),
    ('TAC069', 'TAC páncreas multifásico / protocolo pancreático', 'TAC', 20),
    ('TAC070', 'TAC suprarrenales con protocolo de lavado', 'TAC', 20),
    ('TAC071', 'TAC renal multifásico', 'TAC', 20),
    ('TAC072', 'TAC enterografía', 'TAC', 20),
    ('TAC073', 'TAC colonografía', 'TAC', 20),
    ('TAC074', 'AngioTAC cerebral', 'TAC', 20),
    ('TAC075', 'AngioTAC cuello / vasos de cuello', 'TAC', 20),
    ('TAC076', 'AngioTAC cerebral y vasos de cuello', 'TAC', 20),
    ('TAC077', 'AngioTAC aorta torácica', 'TAC', 20),
    ('TAC078', 'AngioTAC aorta abdominal', 'TAC', 20),
    ('TAC079', 'AngioTAC aorta toracoabdominal', 'TAC', 20),
    ('TAC080', 'AngioTAC aorta y miembros inferiores', 'TAC', 20),
    ('TAC081', 'AngioTAC pulmonar / protocolo TEP', 'TAC', 20),
    ('TAC082', 'AngioTAC coronaria', 'TAC', 20),
    ('TAC083', 'AngioTAC renal', 'TAC', 20),
    ('TAC084', 'AngioTAC mesentérica', 'TAC', 20),
    ('TAC085', 'AngioTAC ilíaca', 'TAC', 20),
    ('TAC086', 'AngioTAC miembros superiores', 'TAC', 20),
    ('TAC087', 'AngioTAC miembros inferiores', 'TAC', 20),
    ('TAC088', 'AngioTAC arterial de miembro superior', 'TAC', 20),
    ('TAC089', 'AngioTAC arterial de miembros inferiores', 'TAC', 20),
    ('USG001', 'USG abdomen completo', 'USG', 30),
    ('USG002', 'USG abdomen superior', 'USG', 30),
    ('USG003', 'USG abdomen inferior', 'USG', 30),
    ('USG004', 'USG hígado y vías biliares', 'USG', 30),
    ('USG005', 'USG hígado', 'USG', 30),
    ('USG006', 'USG vesícula y vías biliares', 'USG', 30),
    ('USG007', 'USG páncreas', 'USG', 30),
    ('USG008', 'USG bazo', 'USG', 30),
    ('USG009', 'USG renal', 'USG', 30),
    ('USG010', 'USG renal bilateral', 'USG', 30),
    ('USG011', 'USG renal y vías urinarias', 'USG', 30),
    ('USG012', 'USG vesical', 'USG', 30),
    ('USG013', 'USG vesical con medición de residuo postmiccional', 'USG', 30),
    ('USG014', 'USG próstata suprapúbico', 'USG', 30),
    ('USG015', 'USG próstata y vejiga con residuo postmiccional', 'USG', 30),
    ('USG016', 'USG pélvico', 'USG', 30),
    ('USG017', 'USG pélvico transabdominal', 'USG', 30),
    ('USG018', 'USG pélvico transvaginal', 'USG', 30),
    ('USG019', 'USG útero y anexos', 'USG', 30),
    ('USG020', 'USG ginecológico transvaginal', 'USG', 30),
    ('USG021', 'USG folicular', 'USG', 30),
    ('USG022', 'USG control folicular', 'USG', 30),
    ('USG023', 'USG endometrial', 'USG', 30),
    ('USG024', 'USG obstétrico', 'USG', 30),
    ('USG025', 'USG obstétrico primer trimestre', 'USG', 30),
    ('USG026', 'USG obstétrico segundo trimestre', 'USG', 30),
    ('USG027', 'USG obstétrico tercer trimestre', 'USG', 30),
    ('USG028', 'USG obstétrico transvaginal', 'USG', 30),
    ('USG029', 'USG obstétrico de viabilidad', 'USG', 30),
    ('USG030', 'USG obstétrico para edad gestacional', 'USG', 30),
    ('USG031', 'USG obstétrico estructural', 'USG', 30),
    ('USG032', 'USG obstétrico morfológico', 'USG', 30),
    ('USG033', 'USG obstétrico con medición de translucencia nucal', 'USG', 30),
    ('USG034', 'USG obstétrico de crecimiento fetal', 'USG', 30),
    ('USG035', 'USG obstétrico de bienestar fetal', 'USG', 30),
    ('USG036', 'USG obstétrico para líquido amniótico', 'USG', 30),
    ('USG037', 'USG embarazo múltiple', 'USG', 30),
    ('USG038', 'USG perfil biofísico fetal', 'USG', 30),
    ('USG039', 'USG mamario', 'USG', 30),
    ('USG040', 'USG mamario bilateral', 'USG', 30),
    ('USG041', 'USG mamario unilateral', 'USG', 30),
    ('USG042', 'USG región axilar', 'USG', 30),
    ('USG043', 'USG tiroides', 'USG', 30),
    ('USG044', 'USG cuello', 'USG', 30),
    ('USG045', 'USG partes blandas de cuello', 'USG', 30),
    ('USG046', 'USG glándulas salivales', 'USG', 30),
    ('USG047', 'USG parótidas', 'USG', 30),
    ('USG048', 'USG submandibular', 'USG', 30),
    ('USG049', 'USG ganglionar / cadenas ganglionares', 'USG', 30),
    ('USG050', 'USG testicular', 'USG', 30),
    ('USG051', 'USG testicular bilateral', 'USG', 30),
    ('USG052', 'USG escrotal', 'USG', 30),
    ('USG053', 'USG inguinoescrotal', 'USG', 30),
    ('USG054', 'USG pene', 'USG', 30),
    ('USG055', 'USG partes blandas', 'USG', 30),
    ('USG056', 'USG pared abdominal', 'USG', 30),
    ('USG057', 'USG región inguinal', 'USG', 30),
    ('USG058', 'USG hernia inguinal', 'USG', 30),
    ('USG059', 'USG hernia umbilical', 'USG', 30),
    ('USG060', 'USG tejido celular subcutáneo', 'USG', 30),
    ('USG061', 'USG masa superficial', 'USG', 30),
    ('USG062', 'USG musculoesquelético', 'USG', 30),
    ('USG063', 'USG hombro', 'USG', 30),
    ('USG064', 'USG codo', 'USG', 30),
    ('USG065', 'USG muñeca', 'USG', 30),
    ('USG066', 'USG mano', 'USG', 30),
    ('USG067', 'USG cadera', 'USG', 30),
    ('USG068', 'USG rodilla', 'USG', 30),
    ('USG069', 'USG tobillo', 'USG', 30),
    ('USG070', 'USG pie', 'USG', 30),
    ('USG071', 'USG tendón', 'USG', 30),
    ('USG072', 'USG músculo', 'USG', 30),
    ('USG073', 'USG articulación', 'USG', 30),
    ('USG074', 'USG tendón de Aquiles', 'USG', 30),
    ('USG075', 'USG manguito rotador', 'USG', 30),
    ('USG076', 'USG transfontanelar', 'USG', 30),
    ('USG077', 'USG cerebral neonatal', 'USG', 30),
    ('USG078', 'USG cadera pediátrica', 'USG', 30),
    ('USG079', 'USG pilórico', 'USG', 30),
    ('USG080', 'USG abdominal pediátrico', 'USG', 30),
    ('USG081', 'USG renal pediátrico', 'USG', 30),
    ('USG082', 'USG Doppler arterial de miembro superior derecho', 'USG', 30),
    ('USG083', 'USG Doppler arterial de miembro superior izquierdo', 'USG', 30),
    ('USG084', 'USG Doppler arterial de miembros superiores bilateral', 'USG', 30),
    ('USG085', 'USG Doppler arterial de miembro inferior derecho', 'USG', 30),
    ('USG086', 'USG Doppler arterial de miembro inferior izquierdo', 'USG', 30),
    ('USG087', 'USG Doppler arterial de miembros inferiores bilateral', 'USG', 30),
    ('USG088', 'USG Doppler de arterias carótidas', 'USG', 30),
    ('USG089', 'USG Doppler carotídeo y vertebral', 'USG', 30),
    ('USG090', 'USG Doppler de aorta abdominal', 'USG', 30),
    ('USG091', 'USG Doppler de arterias renales', 'USG', 30),
    ('USG092', 'USG Doppler de arterias mesentéricas', 'USG', 30),
    ('USG093', 'USG Doppler venoso de miembro superior derecho', 'USG', 30),
    ('USG094', 'USG Doppler venoso de miembro superior izquierdo', 'USG', 30),
    ('USG095', 'USG Doppler venoso de miembros superiores bilateral', 'USG', 30),
    ('USG096', 'USG Doppler venoso de miembro inferior derecho', 'USG', 30),
    ('USG097', 'USG Doppler venoso de miembro inferior izquierdo', 'USG', 30),
    ('USG098', 'USG Doppler venoso de miembros inferiores bilateral', 'USG', 30),
    ('USG099', 'USG Doppler venoso para descartar trombosis venosa profunda', 'USG', 30),
    ('USG100', 'USG Doppler para insuficiencia venosa de miembros inferiores', 'USG', 30),
    ('USG101', 'USG Doppler de sistema venoso superficial y profundo', 'USG', 30),
    ('USG102', 'USG Doppler hepático', 'USG', 30),
    ('USG103', 'USG Doppler portal', 'USG', 30),
    ('USG104', 'USG Doppler hepatoportal', 'USG', 30),
    ('USG105', 'USG Doppler de vena porta', 'USG', 30),
    ('USG106', 'USG Doppler renal', 'USG', 30),
    ('USG107', 'USG Doppler aortoilíaco', 'USG', 30),
    ('USG108', 'USG Doppler obstétrico', 'USG', 30),
    ('USG109', 'USG Doppler fetal', 'USG', 30),
    ('USG110', 'USG Doppler fetoplacentario', 'USG', 30),
    ('USG111', 'USG Doppler de arterias uterinas', 'USG', 30),
    ('USG112', 'USG Doppler de arteria umbilical', 'USG', 30),
    ('USG113', 'USG Doppler de arteria cerebral media fetal', 'USG', 30),
    ('USG114', 'USG Doppler de ductus venoso', 'USG', 30),
    ('USG115', 'USG Doppler obstétrico con perfil hemodinámico fetal', 'USG', 30),
    ('USG116', 'USG Doppler pélvico', 'USG', 30),
    ('USG117', 'USG Doppler transvaginal', 'USG', 30),
    ('USG118', 'USG Doppler uterino', 'USG', 30),
    ('USG119', 'USG Doppler ovárico', 'USG', 30),
    ('USG120', 'USG Doppler testicular', 'USG', 30),
    ('USG121', 'USG Doppler testicular bilateral', 'USG', 30),
    ('USG122', 'USG Doppler escrotal', 'USG', 30),
    ('USG123', 'USG Doppler de cordón espermático', 'USG', 30),
    ('USG124', 'USG Doppler peneano', 'USG', 30),
    ('USG125', 'USG Doppler tiroideo', 'USG', 30),
    ('USG126', 'USG Doppler mamario', 'USG', 30),
    ('USG127', 'USG Doppler de masa / partes blandas', 'USG', 30),
    ('USG128', 'USG Doppler de fístula arteriovenosa', 'USG', 30),
    ('USG129', 'USG Doppler de injerto vascular', 'USG', 30),
]


class Command(BaseCommand):
    help = 'Carga o actualiza el catálogo maestro de estudios de Loreto One.'

    def handle(self, *args, **options):
        creados = 0
        actualizados = 0

        for codigo, nombre, modalidad, tiempo_estimado in CATALOGO:
            _, creado = TipoEstudio.objects.update_or_create(
                codigo=codigo,
                defaults={
                    'nombre': nombre,
                    'modalidad': modalidad,
                    'activo': True,
                    'tiempo_estimado': tiempo_estimado,
                },
            )

            if creado:
                creados += 1
            else:
                actualizados += 1

        self.stdout.write(
            self.style.SUCCESS(
                f'Catálogo cargado correctamente: {creados} creados, '
                f'{actualizados} actualizados, {len(CATALOGO)} estudios maestros.'
            )
        )
