# Generated by Django 6.0.7 on 2026-08-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudio',
            name='tipo_estudio',
            field=models.CharField(help_text='Ejemplo: Radiografía de tórax, Tomografía, Resonancia, etc.', max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='identificacion',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='Registro interno'),
        ),
    ]
