# Generated by Django 6.0.7 on 2026-08-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_estudio_tipo_estudio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudio',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('COMPLETADO', 'Completado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='medico_solicitante',
            field=models.CharField(blank=True, max_length=150, verbose_name='Médico solicitante'),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='tipo_estudio',
            field=models.CharField(help_text='Ejemplo: Radiografía de tórax, tomografía o ultrasonido', max_length=100),
        ),
    ]
