# Generated by Django 6.0.7 on 2026-08-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_estudio_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudio',
            name='medico_solicitante',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Médico solicitante'),
        ),
    ]
