# Generated by Django 6.0.7 on 2026-08-06 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_consulta_estudio_consulta'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('modalidad', models.CharField(choices=[('RX', 'Radiografía'), ('TAC', 'Tomografía'), ('USG', 'Ultrasonido'), ('MASTO', 'Mastografía'), ('FLUORO', 'Fluoroscopia'), ('RM', 'Resonancia Magnética'), ('DXA', 'Densitometría')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('tiempo_estimado', models.PositiveIntegerField(default=10, verbose_name='Tiempo estimado (minutos)')),
            ],
        ),
        migrations.AlterField(
            model_name='consulta',
            name='motivo_consulta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='medico_solicitante',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='tipo_estudio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudios', to='core.tipoestudio'),
        ),
    ]
