# Generated by Django 6.0.7 on 2026-08-07 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tipoestudio_alter_consulta_motivo_consulta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='motivo_consulta',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de consulta'),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='medico_solicitante',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Médico solicitante'),
        ),
        migrations.AlterField(
            model_name='tipoestudio',
            name='modalidad',
            field=models.CharField(choices=[('RX', 'Radiografía'), ('TAC', 'Tomografía'), ('USG', 'Ultrasonido'), ('MASTO', 'Mastografía'), ('FLUORO', 'Fluoroscopia'), ('RM', 'Resonancia magnética'), ('DXA', 'Densitometría')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tipoestudio',
            name='tiempo_estimado',
            field=models.PositiveIntegerField(default=10, verbose_name='Tiempo estimado en minutos'),
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('CONSULTA', 'Consulta médica'), ('IMAGENOLOGIA', 'Imagenología')], max_length=20, verbose_name='Área de atención')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y hora')),
                ('duracion_minutos', models.PositiveIntegerField(default=30, verbose_name='Duración estimada en minutos')),
                ('motivo', models.TextField(blank=True, null=True, verbose_name='Motivo de la cita')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones internas')),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('CONFIRMADA', 'Confirmada'), ('LLEGO', 'Paciente llegó'), ('EN_ESPERA', 'En espera'), ('EN_ATENCION', 'En atención'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada'), ('NO_ASISTIO', 'No asistió')], default='PROGRAMADA', max_length=20)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_creadas', to=settings.AUTH_USER_MODEL)),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Médico o responsable asignado')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='core.paciente')),
                ('tipo_estudio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='core.tipoestudio', verbose_name='Estudio programado')),
            ],
            options={
                'ordering': ['fecha_hora'],
                'indexes': [models.Index(fields=['fecha_hora'], name='core_cita_fecha_h_ed9570_idx'), models.Index(fields=['area', 'estado'], name='core_cita_area_f97c54_idx')],
            },
        ),
    ]
