# Generated by Django 6.0.7 on 2026-08-07 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_consulta_motivo_consulta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='medico',
        ),
        migrations.AddField(
            model_name='cita',
            name='medico_nombre',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Médico'),
        ),
        migrations.AddField(
            model_name='cita',
            name='nombre_paciente',
            field=models.CharField(default='Paciente de prueba', max_length=200, verbose_name='Nombre del paciente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cita',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='area',
            field=models.CharField(choices=[('CONSULTA', 'Consulta médica'), ('TRAUMATOLOGIA', 'Traumatología'), ('DERMATOLOGIA', 'Dermatología'), ('ENDOCRINOLOGIA', 'Endocrinología'), ('RADIOLOGIA', 'Radiología')], max_length=30, verbose_name='Área de atención'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='core.paciente'),
        ),
    ]
