# Generated by Django 6.0.7 on 2026-08-07 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_cita_medico_cita_medico_nombre_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('ultima_actividad', models.DateTimeField(auto_now=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('ip_inicio', models.GenericIPAddressField(blank=True, null=True)),
                ('ip_fin', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_trabajo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-inicio'],
                'indexes': [models.Index(fields=['usuario', 'activa'], name='core_sesion_usuario_d7b87a_idx'), models.Index(fields=['inicio'], name='core_sesion_inicio_1c9296_idx')],
            },
        ),
    ]
