# Generated by Django 6.0.7 on 2026-08-07 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sesiontrabajo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoRadiologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del equipo')),
                ('tipo', models.CharField(choices=[('RX', 'Radiografía'), ('TAC', 'Tomografía'), ('FLUORO', 'Fluoroscopia'), ('MASTO', 'Mastografía'), ('PORTATIL', 'Rayos X portátil'), ('OTRO', 'Otro')], max_length=20)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de serie')),
                ('ubicacion', models.CharField(blank=True, max_length=150, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='estudio',
            name='fecha_finalizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estudio',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estudio',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudios_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Técnico radiólogo'),
        ),
        migrations.AddField(
            model_name='estudio',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudios', to='core.equiporadiologico', verbose_name='Equipo utilizado'),
        ),
        migrations.CreateModel(
            name='BitacoraRadiologica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_realizacion', models.DateTimeField(verbose_name='Fecha y hora de realización')),
                ('paciente_nombre', models.CharField(max_length=250)),
                ('paciente_registro', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('edad', models.PositiveIntegerField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, max_length=20, null=True)),
                ('modalidad', models.CharField(choices=[('RX', 'Radiografía'), ('TAC', 'Tomografía'), ('FLUORO', 'Fluoroscopia'), ('MASTO', 'Mastografía'), ('OTRA', 'Otra')], max_length=20)),
                ('estudio_nombre', models.CharField(max_length=200)),
                ('medico_solicitante', models.CharField(blank=True, max_length=150, null=True)),
                ('tecnico_nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('equipo_nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('kvp', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='kVp')),
                ('mas', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='mAs')),
                ('numero_exposiciones', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de exposiciones')),
                ('proyecciones', models.TextField(blank=True, null=True)),
                ('ctdi_vol', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='CTDIvol')),
                ('dlp', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='DLP')),
                ('uso_contraste', models.BooleanField(blank=True, null=True, verbose_name='Uso de medio de contraste')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('estudio', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bitacora_radiologica', to='core.estudio')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras_radiologicas', to=settings.AUTH_USER_MODEL)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras', to='core.equiporadiologico')),
            ],
            options={
                'ordering': ['-fecha_realizacion'],
                'indexes': [models.Index(fields=['fecha_realizacion'], name='core_bitaco_fecha_r_064204_idx'), models.Index(fields=['modalidad'], name='core_bitaco_modalid_dca59c_idx'), models.Index(fields=['modalidad', 'fecha_realizacion'], name='core_bitaco_modalid_529bf1_idx')],
            },
        ),
    ]
