# Generated by Django 6.0.7 on 2026-08-07 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_equiporadiologico_estudio_fecha_finalizacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='estudios/%Y/%m/%d/', verbose_name='Archivo')),
                ('tipo_archivo', models.CharField(choices=[('DICOM', 'DICOM'), ('IMAGEN', 'Imagen'), ('DOCUMENTO', 'Documento'), ('OTRO', 'Otro')], default='DICOM', max_length=20)),
                ('nombre_original', models.CharField(blank=True, max_length=255, null=True)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='core.estudio')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivos_estudio_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['creado_el'],
            },
        ),
    ]
