# Generated by Django 6.0.7 on 2026-08-11 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_institucion_membresiainstitucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pacientes', to='core.institucion', verbose_name='Institución'),
        ),
    ]
