# Generated by Django 6.0.7 on 2026-08-11 01:06

import django.db.models.deletion
from django.db import migrations, models


def asignar_institucion_inicial(apps, schema_editor):
    Institucion = apps.get_model('core', 'Institucion')
    Paciente = apps.get_model('core', 'Paciente')

    institucion, created = Institucion.objects.get_or_create(
        nombre='Gabinete Radiológico IDUGON',
        defaults={
            'nombre_comercial': 'IDUGON',
            'activa': True,
        }
    )

    Paciente.objects.filter(
        institucion__isnull=True
    ).update(
        institucion=institucion
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_paciente_institucion'),
    ]

    operations = [
        migrations.RunPython(
            asignar_institucion_inicial,
            migrations.RunPython.noop,
        ),

        migrations.AlterField(
            model_name='paciente',
            name='institucion',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='pacientes',
                to='core.institucion',
                verbose_name='Institución',
            ),
        ),
    ]