# Generated by Django 6.0.7 on 2026-08-11 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_paciente_institucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='core.institucion', verbose_name='Institución'),
        ),
    ]
