# Generated by Django 6.0.7 on 2026-08-11 20:26

import django.db.models.deletion
from django.db import migrations, models


def asignar_institucion_a_citas(apps, schema_editor):
    Institucion = apps.get_model('core', 'Institucion')
    Cita = apps.get_model('core', 'Cita')

    institucion, created = Institucion.objects.get_or_create(
        nombre='Gabinete Radiológico IDUGON',
        defaults={
            'nombre_comercial': 'IDUGON',
            'activa': True,
        }
    )

    Cita.objects.filter(
        institucion__isnull=True
    ).update(
        institucion=institucion
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_cita_institucion'),
    ]

    operations = [
        migrations.RunPython(
            asignar_institucion_a_citas,
            migrations.RunPython.noop,
        ),

        migrations.AlterField(
            model_name='cita',
            name='institucion',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='citas',
                to='core.institucion',
                verbose_name='Institución',
            ),
        ),
    ]