# Generated by Django 6.0.7 on 2026-08-11 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_cita_institucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='institucion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='core.institucion', verbose_name='Institución'),
            preserve_default=False,
        ),
    ]
