# Generated by Django 6.0.7 on 2026-08-14 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_cita_institucion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='estudio',
            name='estado_reporte',
            field=models.CharField(choices=[('SIN_REPORTE', 'Sin reporte'), ('PRE_REPORTE', 'Pre-reporte'), ('POR_VALIDAR', 'Por validar'), ('FINAL', 'Reporte final')], default='SIN_REPORTE', max_length=20, verbose_name='Estado del reporte'),
        ),
        migrations.AddField(
            model_name='estudio',
            name='fecha_pre_reporte',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de pre-reporte'),
        ),
        migrations.AddField(
            model_name='estudio',
            name='fecha_reporte_final',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de reporte final'),
        ),
        migrations.AddField(
            model_name='estudio',
            name='pre_reporte',
            field=models.TextField(blank=True, null=True, verbose_name='Pre-reporte técnico'),
        ),
        migrations.AddField(
            model_name='estudio',
            name='pre_reporte_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_reportes_radiologicos', to=settings.AUTH_USER_MODEL, verbose_name='Pre-reporte elaborado por'),
        ),
        migrations.AddField(
            model_name='estudio',
            name='reporte_final',
            field=models.TextField(blank=True, null=True, verbose_name='Reporte radiológico final'),
        ),
        migrations.AddField(
            model_name='estudio',
            name='reporte_final_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_radiologicos_finales', to=settings.AUTH_USER_MODEL, verbose_name='Reporte final validado por'),
        ),
    ]
