# Generated by Django 6.0.7 on 2026-08-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_estudio_estado_reporte_estudio_fecha_pre_reporte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='antecedentes',
            field=models.TextField(blank=True, null=True, verbose_name='Antecedentes'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='diagnostico',
            field=models.TextField(blank=True, null=True, verbose_name='Diagnóstico'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='exploracion_fisica',
            field=models.TextField(blank=True, null=True, verbose_name='Exploración física'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='frecuencia_cardiaca',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Frecuencia cardiaca'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='frecuencia_respiratoria',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Frecuencia respiratoria'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='notas_medicas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas médicas'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='peso_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Peso kg'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='plan_tratamiento',
            field=models.TextField(blank=True, null=True, verbose_name='Plan y tratamiento'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='presion_diastolica',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='TA diastólica'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='presion_sistolica',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='TA sistólica'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='saturacion_oxigeno',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='SpO₂'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='talla_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Talla cm'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='temperatura',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temperatura °C'),
        ),
    ]
