# Generated by Django 6.0.7 on 2026-08-23 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_institucion_horarios_servicio_institucion_logo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamentoreceta',
            name='cantidad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cantidad total'),
        ),
        migrations.AlterField(
            model_name='bitacoraradiologica',
            name='fecha_realizacion',
            field=models.DateTimeField(verbose_name='Fecha y hora de realizaciÃƒÂ³n'),
        ),
        migrations.AlterField(
            model_name='bitacoraradiologica',
            name='modalidad',
            field=models.CharField(choices=[('RX', 'RadiografÃƒÂ\xada'), ('TAC', 'TomografÃƒÂ\xada'), ('FLUORO', 'Fluoroscopia'), ('MASTO', 'MastografÃƒÂ\xada'), ('OTRA', 'Otra')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bitacoraradiologica',
            name='numero_exposiciones',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='NÃƒÂºmero de exposiciones'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='area',
            field=models.CharField(choices=[('CONSULTA', 'Consulta mÃƒÂ©dica'), ('TRAUMATOLOGIA', 'TraumatologÃƒÂ\xada'), ('DERMATOLOGIA', 'DermatologÃƒÂ\xada'), ('ENDOCRINOLOGIA', 'EndocrinologÃƒÂ\xada'), ('RADIOLOGIA', 'RadiologÃƒÂ\xada')], max_length=30, verbose_name='ÃƒÂ\x81rea de atenciÃƒÂ³n'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='duracion_minutos',
            field=models.PositiveIntegerField(default=30, verbose_name='DuraciÃƒÂ³n estimada en minutos'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('PROGRAMADA', 'Programada'), ('CONFIRMADA', 'Confirmada'), ('LLEGO', 'Paciente llegÃƒÂ³'), ('EN_ESPERA', 'En espera'), ('EN_ATENCION', 'En atenciÃƒÂ³n'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada'), ('NO_ASISTIO', 'No asistiÃƒÂ³')], default='PROGRAMADA', max_length=20),
        ),
        migrations.AlterField(
            model_name='cita',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='core.institucion', verbose_name='InstituciÃƒÂ³n'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='medico_nombre',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='MÃƒÂ©dico'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='TelÃƒÂ©fono'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='diagnostico',
            field=models.TextField(blank=True, null=True, verbose_name='DiagnÃƒÂ³stico'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='exploracion_fisica',
            field=models.TextField(blank=True, null=True, verbose_name='ExploraciÃƒÂ³n fÃƒÂ\xadsica'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='notas_medicas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas mÃƒÂ©dicas'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='presion_diastolica',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='TA diastÃƒÂ³lica'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='presion_sistolica',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='TA sistÃƒÂ³lica'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='saturacion_oxigeno',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='SpOÃ¢â€šâ€š'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='temperatura',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temperatura Ã‚Â°C'),
        ),
        migrations.AlterField(
            model_name='equiporadiologico',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='NÃƒÂºmero de serie'),
        ),
        migrations.AlterField(
            model_name='equiporadiologico',
            name='tipo',
            field=models.CharField(choices=[('RX', 'RadiografÃƒÂ\xada'), ('TAC', 'TomografÃƒÂ\xada'), ('FLUORO', 'Fluoroscopia'), ('MASTO', 'MastografÃƒÂ\xada'), ('PORTATIL', 'Rayos X portÃƒÂ¡til'), ('OTRO', 'Otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='medico_solicitante',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='MÃƒÂ©dico solicitante'),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='pre_reporte',
            field=models.TextField(blank=True, null=True, verbose_name='Pre-reporte tÃƒÂ©cnico'),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='reporte_final',
            field=models.TextField(blank=True, null=True, verbose_name='Reporte radiolÃƒÂ³gico final'),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudios_realizados', to=settings.AUTH_USER_MODEL, verbose_name='TÃƒÂ©cnico radiÃƒÂ³logo'),
        ),
        migrations.AlterField(
            model_name='estudiosolicitado',
            name='indicaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Indicaciones especÃ\xadficas'),
        ),
        migrations.AlterField(
            model_name='estudiosolicitado',
            name='region_o_detalle',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='RegiÃ³n, muestra o detalle'),
        ),
        migrations.AlterField(
            model_name='indicacionmedica',
            name='indicaciones',
            field=models.TextField(verbose_name='Indicaciones mÃ©dicas'),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre de la instituciÃƒÂ³n'),
        ),
        migrations.AlterField(
            model_name='medicamentoreceta',
            name='duracion',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='DuraciÃ³n'),
        ),
        migrations.AlterField(
            model_name='medicamentoreceta',
            name='presentacion',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='PresentaciÃ³n'),
        ),
        migrations.AlterField(
            model_name='medicamentoreceta',
            name='via',
            field=models.CharField(blank=True, choices=[('ORAL', 'Oral'), ('SUBLINGUAL', 'Sublingual'), ('TOPICA', 'TÃ³pica'), ('INHALADA', 'Inhalada'), ('OFTALMICA', 'OftÃ¡lmica'), ('OTICA', 'Ã“tica'), ('NASAL', 'Nasal'), ('RECTAL', 'Rectal'), ('VAGINAL', 'Vaginal'), ('INTRAMUSCULAR', 'Intramuscular'), ('INTRAVENOSA', 'Intravenosa'), ('SUBCUTANEA', 'SubcutÃ¡nea'), ('OTRA', 'Otra')], max_length=30, null=True, verbose_name='VÃ\xada de administraciÃ³n'),
        ),
        migrations.AlterField(
            model_name='membresiainstitucion',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('RECEPCION', 'RecepciÃƒÂ³n'), ('MEDICO', 'MÃƒÂ©dico'), ('RADIOLOGIA', 'RadiologÃƒÂ\xada'), ('TECNICO', 'TÃƒÂ©cnico'), ('ENFERMERIA', 'EnfermerÃƒÂ\xada'), ('OTRO', 'Otro')], default='OTRO', max_length=20),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pacientes', to='core.institucion', verbose_name='InstituciÃƒÂ³n'),
        ),
        migrations.AlterField(
            model_name='solicitudestudio',
            name='motivo_clinico',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo clÃ\xadnico / diagnÃ³stico presuntivo'),
        ),
        migrations.AlterField(
            model_name='solicitudestudio',
            name='tipo',
            field=models.CharField(choices=[('LABORATORIO', 'Laboratorio clÃ\xadnico'), ('IMAGEN', 'ImagenologÃ\xada'), ('PATOLOGIA', 'PatologÃ\xada'), ('CARDIOLOGIA', 'CardiologÃ\xada'), ('OTRO', 'Otro estudio o procedimiento')], max_length=30),
        ),
        migrations.AlterField(
            model_name='tipoestudio',
            name='modalidad',
            field=models.CharField(choices=[('RX', 'RadiografÃƒÂ\xada'), ('TAC', 'TomografÃƒÂ\xada'), ('USG', 'Ultrasonido'), ('MASTO', 'MastografÃƒÂ\xada'), ('FLUORO', 'Fluoroscopia'), ('RM', 'Resonancia magnÃƒÂ©tica'), ('DXA', 'DensitometrÃƒÂ\xada')], max_length=20),
        ),
    ]
