# Generated by Django 6.0.7 on 2026-08-24 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_medicamentoreceta_cantidad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacoraradiologica',
            name='fecha_realizacion',
            field=models.DateTimeField(verbose_name='Fecha y hora de realización'),
        ),
        migrations.AlterField(
            model_name='bitacoraradiologica',
            name='modalidad',
            field=models.CharField(choices=[('RX', 'Radiografía'), ('TAC', 'Tomografía'), ('FLUORO', 'Fluoroscopia'), ('MASTO', 'Mastografía'), ('OTRA', 'Otra')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bitacoraradiologica',
            name='numero_exposiciones',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de exposiciones'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='area',
            field=models.CharField(choices=[('CONSULTA', 'Consulta médica'), ('TRAUMATOLOGIA', 'Traumatología'), ('DERMATOLOGIA', 'Dermatología'), ('ENDOCRINOLOGIA', 'Endocrinología'), ('RADIOLOGIA', 'Radiología')], max_length=30, verbose_name='Área de atención'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='duracion_minutos',
            field=models.PositiveIntegerField(default=30, verbose_name='Duración estimada en minutos'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('PROGRAMADA', 'Programada'), ('CONFIRMADA', 'Confirmada'), ('LLEGO', 'Paciente llegó'), ('EN_ESPERA', 'En espera'), ('EN_ATENCION', 'En atención'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada'), ('NO_ASISTIO', 'No asistió')], default='PROGRAMADA', max_length=20),
        ),
        migrations.AlterField(
            model_name='cita',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='core.institucion', verbose_name='Institución'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='medico_nombre',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Médico'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='diagnostico',
            field=models.TextField(blank=True, null=True, verbose_name='Diagnóstico'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='exploracion_fisica',
            field=models.TextField(blank=True, null=True, verbose_name='Exploración física'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='notas_medicas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas médicas'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='presion_diastolica',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='TA diastólica'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='presion_sistolica',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='TA sistólica'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='saturacion_oxigeno',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='SpO₂'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='temperatura',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temperatura °C'),
        ),
        migrations.AlterField(
            model_name='equiporadiologico',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de serie'),
        ),
        migrations.AlterField(
            model_name='equiporadiologico',
            name='tipo',
            field=models.CharField(choices=[('RX', 'Radiografía'), ('TAC', 'Tomografía'), ('FLUORO', 'Fluoroscopia'), ('MASTO', 'Mastografía'), ('PORTATIL', 'Rayos X portátil'), ('OTRO', 'Otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='medico_solicitante',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Médico solicitante'),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='pre_reporte',
            field=models.TextField(blank=True, null=True, verbose_name='Pre-reporte técnico'),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='reporte_final',
            field=models.TextField(blank=True, null=True, verbose_name='Reporte radiológico final'),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudios_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Técnico radiólogo'),
        ),
        migrations.AlterField(
            model_name='estudiosolicitado',
            name='indicaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Indicaciones específicas'),
        ),
        migrations.AlterField(
            model_name='estudiosolicitado',
            name='region_o_detalle',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Región, muestra o detalle'),
        ),
        migrations.AlterField(
            model_name='indicacionmedica',
            name='indicaciones',
            field=models.TextField(verbose_name='Indicaciones médicas'),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre de la institución'),
        ),
        migrations.AlterField(
            model_name='medicamentoreceta',
            name='duracion',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Duración'),
        ),
        migrations.AlterField(
            model_name='medicamentoreceta',
            name='presentacion',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Presentación'),
        ),
        migrations.AlterField(
            model_name='medicamentoreceta',
            name='via',
            field=models.CharField(blank=True, choices=[('ORAL', 'Oral'), ('SUBLINGUAL', 'Sublingual'), ('TOPICA', 'Tópica'), ('INHALADA', 'Inhalada'), ('OFTALMICA', 'Oftálmica'), ('OTICA', 'Ótica'), ('NASAL', 'Nasal'), ('RECTAL', 'Rectal'), ('VAGINAL', 'Vaginal'), ('INTRAMUSCULAR', 'Intramuscular'), ('INTRAVENOSA', 'Intravenosa'), ('SUBCUTANEA', 'Subcutánea'), ('OTRA', 'Otra')], max_length=30, null=True, verbose_name='Vía de administración'),
        ),
        migrations.AlterField(
            model_name='membresiainstitucion',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('RECEPCION', 'Recepción'), ('MEDICO', 'Médico'), ('RADIOLOGIA', 'Radiología'), ('TECNICO', 'Técnico'), ('ENFERMERIA', 'Enfermería'), ('OTRO', 'Otro')], default='OTRO', max_length=20),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pacientes', to='core.institucion', verbose_name='Institución'),
        ),
        migrations.AlterField(
            model_name='solicitudestudio',
            name='motivo_clinico',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo clínico / diagnóstico presuntivo'),
        ),
        migrations.AlterField(
            model_name='solicitudestudio',
            name='tipo',
            field=models.CharField(choices=[('LABORATORIO', 'Laboratorio clínico'), ('IMAGEN', 'Imagenología'), ('PATOLOGIA', 'Patología'), ('CARDIOLOGIA', 'Cardiología'), ('OTRO', 'Otro estudio o procedimiento')], max_length=30),
        ),
        migrations.AlterField(
            model_name='tipoestudio',
            name='modalidad',
            field=models.CharField(choices=[('RX', 'Radiografía'), ('TAC', 'Tomografía'), ('USG', 'Ultrasonido'), ('MASTO', 'Mastografía'), ('FLUORO', 'Fluoroscopia'), ('RM', 'Resonancia magnética'), ('DXA', 'Densitometría')], max_length=20),
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del servicio')),
                ('tipo', models.CharField(choices=[('CONSULTA', 'Consulta médica'), ('RX', 'Radiografía'), ('USG', 'Ultrasonido'), ('TAC', 'Tomografía'), ('MASTO', 'Mastografía'), ('RM', 'Resonancia magnética'), ('FLUORO', 'Fluoroscopia'), ('PROCEDIMIENTO', 'Procedimiento'), ('INMOVILIZACION', 'Inmovilización'), ('MATERIAL', 'Material'), ('OTRO', 'Otro')], default='OTRO', max_length=30)),
                ('precio_base', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio base')),
                ('precio_editable', models.BooleanField(default=False, verbose_name='Permitir precio manual')),
                ('activo', models.BooleanField(default=True)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='core.institucion', verbose_name='Institución')),
                ('tipo_estudio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_comerciales', to='core.tipoestudio', verbose_name='Tipo de estudio relacionado')),
            ],
            options={
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='CargoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250, verbose_name='Concepto')),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio unitario')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('origen', models.CharField(choices=[('RECEPCION', 'Recepción'), ('MEDICO', 'Médico'), ('RADIOLOGIA', 'Radiología'), ('TECNICO', 'Técnico radiológico'), ('ENFERMERIA', 'Enfermería'), ('SISTEMA', 'Sistema'), ('OTRO', 'Otro')], default='SISTEMA', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
                ('agregado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargos_agregados', to=settings.AUTH_USER_MODEL, verbose_name='Agregado por')),
                ('consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargos', to='core.consulta')),
                ('estudio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargos', to='core.estudio')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargos_pacientes', to='core.institucion', verbose_name='Institución')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargos', to='core.paciente', verbose_name='Paciente')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargos', to='core.servicio', verbose_name='Servicio del catálogo')),
            ],
            options={
                'ordering': ['-creado_el'],
            },
        ),
        migrations.AddIndex(
            model_name='servicio',
            index=models.Index(fields=['institucion', 'tipo', 'activo'], name='core_servic_institu_611cb7_idx'),
        ),
        migrations.AddIndex(
            model_name='cargopaciente',
            index=models.Index(fields=['institucion', 'paciente', 'estado'], name='core_cargop_institu_4ba499_idx'),
        ),
        migrations.AddIndex(
            model_name='cargopaciente',
            index=models.Index(fields=['creado_el'], name='core_cargop_creado__f7e494_idx'),
        ),
    ]
