# Generated by Django 6.0.7 on 2026-08-25 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_institucion_rfc_cobro_cargopaciente_cobro'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cobro',
            new_name='core_cobro_institu_48f8cb_idx',
            old_name='core_cobro_institu_9a48b6_idx',
        ),
        migrations.RenameIndex(
            model_name='cobro',
            new_name='core_cobro_folio_37367e_idx',
            old_name='core_cobro_folio_86e6df_idx',
        ),
    ]
