# Generated by Django 6.0.7 on 2026-08-27 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_dicom_estudio_serie_instancia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EliminacionSerieDicom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_instance_uid', models.CharField(max_length=128)),
                ('numero_serie', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=250)),
                ('modalidad', models.CharField(blank=True, max_length=20)),
                ('cantidad_instancias', models.PositiveIntegerField(default=0)),
                ('motivo', models.TextField()),
                ('metadatos', models.JSONField(blank=True, default=dict)),
                ('eliminado_el', models.DateTimeField(auto_now_add=True)),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eliminaciones_series_dicom', to='core.estudio')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eliminaciones_series_dicom', to='core.institucion')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eliminaciones_series_dicom', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-eliminado_el'],
                'indexes': [models.Index(fields=['institucion', 'eliminado_el'], name='dicom_del_inst_fecha_idx')],
            },
        ),
    ]
