# Generated by Django 6.0.7 on 2026-08-27 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_eliminacionseriedicom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteRadiologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('FINAL', 'Final')], default='BORRADOR', max_length=15)),
                ('hallazgos_html', models.TextField(blank=True)),
                ('impresion_html', models.TextField(blank=True)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
                ('finalizado_el', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('datos_snapshot', models.JSONField(blank=True, default=dict)),
                ('elaborado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_radiologicos_elaborados', to=settings.AUTH_USER_MODEL)),
                ('estudio', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reporte_radiologico', to='core.estudio')),
                ('finalizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_radiologicos_finalizados', to=settings.AUTH_USER_MODEL)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes_radiologicos', to='core.institucion')),
            ],
            options={
                'ordering': ['-actualizado_el'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaReporteRadiologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('modalidad', models.CharField(blank=True, max_length=20)),
                ('hallazgos_html', models.TextField(blank=True)),
                ('impresion_html', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('creada_el', models.DateTimeField(auto_now_add=True)),
                ('actualizada_el', models.DateTimeField(auto_now=True)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantillas_reportes_radiologicos', to=settings.AUTH_USER_MODEL)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_reportes_radiologicos', to='core.institucion')),
                ('tipo_estudio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantillas_reportes_radiologicos', to='core.tipoestudio')),
            ],
            options={
                'ordering': ['nombre'],
                'constraints': [models.UniqueConstraint(fields=('institucion', 'nombre'), name='unique_plantilla_reporte_institucion')],
            },
        ),
        migrations.CreateModel(
            name='RevisionReporteRadiologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('estado', models.CharField(max_length=15)),
                ('hallazgos_html', models.TextField(blank=True)),
                ('impresion_html', models.TextField(blank=True)),
                ('datos_snapshot', models.JSONField(blank=True, default=dict)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisiones_reportes_radiologicos', to=settings.AUTH_USER_MODEL)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisiones', to='core.reporteradiologico')),
            ],
            options={
                'ordering': ['-version'],
                'constraints': [models.UniqueConstraint(fields=('reporte', 'version'), name='unique_revision_reporte_version')],
            },
        ),
    ]
