# Generated by Django 6.0.7 on 2026-08-28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_reporteradiologico_plantillareporteradiologico_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaDigitalEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('codigo_hash', models.CharField(max_length=128)),
                ('vence_el', models.DateTimeField()),
                ('activa', models.BooleanField(default=True)),
                ('intentos_fallidos', models.PositiveSmallIntegerField(default=0)),
                ('bloqueada_el', models.DateTimeField(blank=True, null=True)),
                ('accesos', models.PositiveIntegerField(default=0)),
                ('ultimo_acceso_el', models.DateTimeField(blank=True, null=True)),
                ('creada_el', models.DateTimeField(auto_now_add=True)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_digitales_estudios_creadas', to=settings.AUTH_USER_MODEL)),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas_digitales', to='core.estudio')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas_digitales_estudios', to='core.institucion')),
            ],
            options={
                'ordering': ['-creada_el'],
                'indexes': [
                    models.Index(fields=['institucion', 'estudio', 'activa'], name='core_entrega_inst_est_act_idx'),
                    models.Index(fields=['vence_el'], name='core_entrega_vence_idx'),
                ],
            },
        ),
    ]
