# Generated by Django 6.0.7 on 2026-09-10 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_control_entregas_digitales'),
        ('core', '0035_radiologia_registro_entrega_mantenimiento'),
    ]

    operations = [
    ]
