"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.
"""

from pathlib import Path
import os
import dj_database_url


# ============================================================
# RUTAS DEL PROYECTO
# ============================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# ============================================================
# ENTORNO: LOCAL / PRODUCCIÓN
# ============================================================

IS_PRODUCTION = os.environ.get('RENDER') == 'true'


# ============================================================
# SEGURIDAD
# ============================================================

SECRET_KEY = os.environ.get('SECRET_KEY')

if not SECRET_KEY:
    if IS_PRODUCTION:
        raise RuntimeError(
            'La variable de entorno SECRET_KEY no está configurada.'
        )

    SECRET_KEY = (
        'django-insecure-local-development-only-'
        'loreto-one-do-not-use-in-production'
    )


DEBUG = not IS_PRODUCTION


# ============================================================
# HOSTS
# ============================================================

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
]

RENDER_EXTERNAL_HOSTNAME = os.environ.get(
    'RENDER_EXTERNAL_HOSTNAME'
)

if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(
        RENDER_EXTERNAL_HOSTNAME
    )

# Dejamos también explícito el dominio actual.
if 'loreto-pacs.onrender.com' not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(
        'loreto-pacs.onrender.com'
    )


# ============================================================
# RENDER / HTTPS / CSRF
# ============================================================

CSRF_TRUSTED_ORIGINS = [
    'https://loreto-pacs.onrender.com',
]


SECURE_PROXY_SSL_HEADER = (
    'HTTP_X_FORWARDED_PROTO',
    'https',
)


CSRF_COOKIE_SECURE = IS_PRODUCTION
SESSION_COOKIE_SECURE = IS_PRODUCTION

CSRF_COOKIE_HTTPONLY = False
SESSION_COOKIE_HTTPONLY = True

CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SAMESITE = 'Lax'


# ============================================================
# APLICACIONES
# ============================================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Almacenamiento de archivos en Cloudflare R2 / S3.
    'storages',

    'core',
    'pacientes',
    'recepcion',
]


# ============================================================
# MIDDLEWARE
# ============================================================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',

    'whitenoise.middleware.WhiteNoiseMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ============================================================
# URLS
# ============================================================

ROOT_URLCONF = 'config.urls'


# ============================================================
# AUTENTICACIÓN
# ============================================================

# LoretoOne utiliza su propia vista de inicio de sesión en /login/.
# Esto evita que @login_required intente enviar al usuario a la
# ruta predeterminada de Django: /accounts/login/.
LOGIN_URL = '/login/'


# ============================================================
# TEMPLATES
# ============================================================

TEMPLATES = [
    {
        'BACKEND':
            'django.template.backends.django.DjangoTemplates',

        'DIRS': [],

        'APP_DIRS': True,

        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# ============================================================
# WSGI
# ============================================================

WSGI_APPLICATION = 'config.wsgi.application'


# ============================================================
# BASE DE DATOS
# ============================================================

DATABASES = {
    'default': dj_database_url.config(
        default=(
            f"sqlite:///{BASE_DIR / 'db.sqlite3'}"
        ),
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# ============================================================
# VALIDACIÓN DE CONTRASEÑAS
# ============================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'UserAttributeSimilarityValidator'
        ),
    },

    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'MinimumLengthValidator'
        ),
    },

    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'CommonPasswordValidator'
        ),
    },

    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'NumericPasswordValidator'
        ),
    },
]


# ============================================================
# INTERNACIONALIZACIÓN
# ============================================================

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# ============================================================
# ARCHIVOS ESTÁTICOS
# ============================================================

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'


# ============================================================
# ALMACENAMIENTO DE ARCHIVOS
# ============================================================
#
# LOCAL:
#   Los archivos continúan guardándose en el sistema de archivos
#   de la computadora.
#
# PRODUCCIÓN / RENDER:
#   Los archivos médicos se almacenan en Cloudflare R2.
#
# Los archivos de estudios permanecen privados. Django genera
# URLs firmadas temporales cuando necesita mostrarlos.
# ============================================================

if IS_PRODUCTION:

    STORAGES = {
        'default': {
            'BACKEND': (
                'storages.backends.s3.S3Storage'
            ),

            'OPTIONS': {
                'access_key': os.environ.get(
                    'AWS_ACCESS_KEY_ID'
                ),

                'secret_key': os.environ.get(
                    'AWS_SECRET_ACCESS_KEY'
                ),

                'bucket_name': os.environ.get(
                    'AWS_STORAGE_BUCKET_NAME'
                ),

                'endpoint_url': os.environ.get(
                    'AWS_S3_ENDPOINT_URL'
                ),

                'region_name': os.environ.get(
                    'AWS_S3_REGION_NAME',
                    'auto'
                ),

                'addressing_style': os.environ.get(
                    'AWS_S3_ADDRESSING_STYLE',
                    'virtual'
                ),

                # El bucket permanece privado.
                # Las URLs generadas serán firmadas.
                'querystring_auth': True,

                # URL válida durante 15 minutos.
                'querystring_expire': 900,

                # Cloudflare R2 no utiliza ACL tradicionales.
                'default_acl': None,

                # Evita sobrescribir accidentalmente
                # archivos con el mismo nombre.
                'file_overwrite': False,
            },
        },

        'staticfiles': {
            'BACKEND': (
                'whitenoise.storage.'
                'CompressedManifestStaticFilesStorage'
            ),
        },
    }

else:

    STORAGES = {
        'default': {
            'BACKEND': (
                'django.core.files.storage.'
                'FileSystemStorage'
            ),
        },

        'staticfiles': {
            'BACKEND': (
                'whitenoise.storage.'
                'CompressedManifestStaticFilesStorage'
            ),
        },
    }